name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set the Node.js version (adjust if needed)

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Build the project
        run: npm run build  # Build the project for production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Use the action to deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate
          publish_dir: ./dist  # Directory to publish (built project)
          publish_branch: gh-pages  # The branch that will hold the GitHub Pages content
